"use client";

// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {SearchProvider} from "@/context/SearchContext"


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SearchProvider>
        {children}
        </SearchProvider>

        <footer className="text-center p-2 mt-10">
          <p className="text-center text-gray-500 text-sm">

            © 2024 All Rights Reserved SHAHABUDDIN
          </p>
        </footer>
      </body>
    </html>
  );
}
